#!/bin/bash
#show panel on bottom left side

xdotool mousemove 1300 800
sleep 2
eval $(xdotool getmouselocation --shell)
if [[ $X == 1300 && $Y == 767 ]]; then      #if mouse is still in panel move it to another location
    xdotool mousemove 800 400   
fi

